mysql:
  host: "127.0.0.1"
  port: 3306
  db: gvbDB
  user: root
  password: root
  logLevel: dev
logger:
  level: info
  prefix: '[gvb]'
  director: log
  showLine: true
  logInConsole: true
system:
  host: "0.0.0.0"
  port: 8080
  env: dev